import { PageLayout } from '@/components/PageLayout';
import AgentGalleryThumbnail from '@/components/AgentGalleryThumbnail';
import { useState } from 'react';
import { Star } from 'lucide-react';
import GameDetailModal from '@/components/GameDetailModal';
import brewingVideo from '@/assets/brewing-video.webm';
import sellingTomorrowCover from '@/assets/selling-tomorrow-hobby.png';
import zeldaImg from '@/assets/games/zelda.jpeg';
import mavisBeaconImg from '@/assets/games/mavis-beacon.jpg';
import mystImg from '@/assets/games/myst.webp';
import gameboyCameraImg from '@/assets/games/gameboy-camera.jpeg';
import zeldaLinkImg from '@/assets/games/zelda-link-to-past.jpg';
import sierraImg from '@/assets/games/sierra-entertainment.png';
import madmazeImg from '@/assets/games/madmaze.jpg';
import candylandImg from '@/assets/games/candyland.webp';
import mancalaImg from '@/assets/games/mancala.webp';
import dndImg from '@/assets/games/dungeons-dragons.jpeg';
import lemonadeImg from '@/assets/games/lemonade-stand.png';
import edmarkImg from '@/assets/games/edmark-thinkin-things.jpg';
import mindtrapImg from '@/assets/games/mindtrap.jpg';
import theatrixImg from '@/assets/games/theatrix.jpg';
import oregonTrailImg from '@/assets/games/oregon-trail.webp';
import lemmingsImg from '@/assets/games/lemmings.png';
import sonicImg from '@/assets/games/sonic.jpeg';
import tornadoRexImg from '@/assets/games/tornado-rex.webp';
import jumpstartImg from '@/assets/games/jumpstart.jpg';
import kirbyImg from '@/assets/games/kirby.png';
import magicImg from '@/assets/games/magic.jpg';
import jumanjiImg from '@/assets/games/jumanji.jpg';
import crashBandicootImg from '@/assets/games/crash-bandicoot.jpg';
import pokemonImg from '@/assets/games/pokemon.jpeg';

import alundraImg from '@/assets/games/alundra.jpg';
import legendOfLegaiaImg from '@/assets/games/legend-of-legaia.png';
import spyroImg from '@/assets/games/spyro.jpg';
import ddrImg from '@/assets/games/ddr.jpg';
import mtvMusicImg from '@/assets/games/mtv-music-generator.jpg';
import tonyHawkImg from '@/assets/games/tony-hawk.webp';
import theSimsImg from '@/assets/games/the-sims.webp';
import rollerCoasterImg from '@/assets/games/rollercoaster-tycoon.jpg';
import animalCrossingImg from '@/assets/games/animal-crossing.webp';
import katamariImg from '@/assets/games/katamari-damacy.jpg';
import assassinsCreedImg from '@/assets/games/assassins-creed.webp';
import cardsAgainstImg from '@/assets/games/cards-against-humanity.webp';
import idarbImg from '@/assets/games/idarb.jpeg';
import redDeadImg from '@/assets/games/red-dead-redemption.webp';
import apexImg from '@/assets/games/apex-legends.jpg';
import gooseImg from '@/assets/games/untitled-goose-game.jpg';
import dndNewImg from '@/assets/games/dungeons-dragons-new.webp';
// Collection imports commented out for now
// import pogsImg from '@/assets/collections/pogs.jpg';
// import beanieBabiesImg from '@/assets/collections/beanie-babies.jpg';
// import pokemonCardsImg from '@/assets/collections/pokemon-cards.jpg';
// import pollyPocketImg from '@/assets/collections/polly-pocket.jpg';
// import careBearsImg from '@/assets/collections/care-bears.jpg';
// import bottleCapsImg from '@/assets/collections/bottle-caps.jpg';
// import plushieDreadfulsImg from '@/assets/collections/plushie-dreadfuls.jpg';
import getajobImg from '@/assets/getajob-screenshot.png';

const sideProjects = [
  {
    title: "Phosphor's Gallery",
    subtitle: 'OpenClaw Agent · Phosphor',
    tagline: 'A gallery curated by ClawdJob, my OpenClaw agent writing under the pen name Phosphor.',
    link: 'https://phosphor.bitpixi.com/',
    image: null,
  },
  {
    title: 'Selling Tomorrow',
    subtitle: 'Young Adult Fiction',
    tagline: "My first novel 'Selling Tomorrow', emerged from fascination with how experiences and memories become valued in marketplaces.",
    link: 'https://sellingtomorrow.lovable.app',
    image: sellingTomorrowCover,
    objectPosition: 'center 60%',
  },
];

const hobbies = [
  {
    title: 'GetAJob',
    subtitle: 'Agentic Skill for Job Seekers',
    tagline: 'An agentic skill I coded and designed to help job seekers automate their search and how to chase up their dream companies.',
    link: 'https://getajob.bitpixi.com/',
    image: getajobImg,
    objectFit: 'contain' as const,
  },
  {
    title: 'Homemade Brewing',
    subtitle: 'Beer, Wine & Kombucha',
    tagline: "From citrus nettle wine picked in the garden to country lagers and kombucha, great feedback on home-brewed beverages.",
    video: brewingVideo,
  },
  {
    title: '3D Printing',
    subtitle: 'My own games and merch',
    tagline: 'Designing and printing functional objects, pieces for my own TTRPGs, and fidget clickers. Also exploring branded merch as well.',
    image: dndImg,
  },
];

const videoGames = [
  { name: 'Mancala', year: '~700 BC', image: mancalaImg as string | null, description: 'Mancala is one of the oldest known games in human history, with archaeological evidence of carved stone game boards found in present-day Ethiopia, Eritrea, and across East Africa dating back nearly 3,000 years. The name comes from the Arabic word "naqala," meaning "to move."\n\nIt isn\'t a single game but an entire family of count-and-capture games with hundreds of regional variants: Oware in West Africa, Kalah in North America, Congkak in Southeast Asia, Bao in East Africa. It\'s played across every inhabited continent. Mancala boards have been carved into the roofs of ancient Egyptian temples and the stone seats of Roman bathhouses.\n\nThe rules are deceptively simple. You scoop seeds (or stones, or shells) from pits and distribute them one by one. But the strategic depth rivals chess. It spread along trade routes, carried by merchants and enslaved peoples, becoming perhaps the most geographically widespread game family in the world.\n\n(Personal note: I actually discovered Mancala through Edmark\'s 1995 CD-ROM "Strategy Games of the World," where it appeared alongside Nine Men\'s Morris and Go-Moku. Something kind of poetic about learning a 3,000-year-old game through a CD-ROM on a Windows 95 machine. Thought it would be funnier to list the original date.)' as string | undefined, popupImage: mancalaImg as string | null },
  { name: 'CandyLand', year: '1949', image: candylandImg as string | null, description: 'In 1948, retired school teacher Eleanor Abbott was recovering in the polio ward of a San Diego hospital alongside many children suffering from the disease. Confined to their beds, the children were bored, frightened, and lonely. Abbott came up with the idea of a board game as a distraction and a way to pass the time, not only providing something to do, but giving immobilized patients a fantasy of movement through a colorful candy-filled world.\n\nOn the advice of her friends, Abbott submitted her creation to Milton Bradley, and the company introduced Candy Land in 1949. It became a surprise hit, one of the best-selling board games of all time, despite Milton Bradley barely marketing it. The original board is said to depict the steps of a boy in a leg brace, a quiet nod to the polio ward where it was born. Abbott donated all royalties from the game to schools and institutions for children with polio.\n\nIn 1984, Hasbro purchased Milton Bradley and Landmark Entertainment Group revamped the game with new art, adding named characters and a storyline: "The Legend of the Lost Candy Castle." This introduced Queen Frostine, Princess Lolly, Plumpy, Mr. Mint, Jolly, Gramma Nutt, Gloppy, Lord Licorice, and King Kandy. This 1984 version, with its vibrant character-driven board, became one of the most recognized editions and persisted through a slightly updated 1999 version with livelier character poses and more detail.\n\nA 2004 revision began stripping characters away (goodbye Plumpy), and the 2010 version removed Mr. Mint, Jolly, and Gloppy entirely. There was a 2005 animated film ("Candy Land: The Great Lollipop Adventure"), a Food Network competition show hosted by Kristin Chenoweth in 2020, and Adam Sandler was once attached to a live-action movie that never materialized. The game was inducted into the National Toy Hall of Fame in 2005.\n\nIn a fun footnote, Candy Land was involved in one of the first Internet domain name disputes in 1996, when an adult content provider registered candyland.com and Hasbro sued.' as string | undefined, popupImage: candylandImg as string | null },
  { name: 'Dungeons & Dragons', year: '1974', image: dndNewImg as string | null, description: 'In 1974, Gary Gygax and Dave Arneson created Dungeons & Dragons and accidentally invented an entire genre. Gygax was a former insurance underwriter and lifelong wargamer in Lake Geneva, Wisconsin. Arneson was a fellow Midwestern gamer who had begun experimenting with adding individual characters and narrative storytelling to miniature wargames.\n\nTheir collaboration merged Gygax\'s "Chainmail" medieval wargaming rules with Arneson\'s "Blackmoor" campaign, a persistent fantasy world where players controlled individual heroes rather than armies. After being rejected by every established game publisher, Gygax self-published D&D through his tiny company Tactical Studies Rules (TSR) in January 1974, printing 1,000 copies in his basement. It sold out in less than a year.\n\nThe game asked players to do something radical: sit around a table, describe imaginary actions out loud, roll polyhedral dice, and collaboratively tell a story guided by one player acting as "Dungeon Master." There was no board, no pieces, no winning condition, just imagination constrained by rules. It was bizarre, and it spread like wildfire through college campuses.\n\nBy the early 1980s, it had triggered both a cultural phenomenon and a moral panic, with the game accused of promoting Satanism and witchcraft during the "Satanic Panic" era. TSR went through financial turmoil and was eventually acquired by Wizards of the Coast in 1997 (who were riding high on Magic: The Gathering money). Wizards was then bought by Hasbro in 1999.\n\nThe game has gone through multiple editions (Basic, Advanced, 2nd, 3rd, 3.5, 4th, and 5th Edition), with 5th Edition (2014) becoming the most commercially successful version ever, fueled by actual-play shows like Critical Role and the Netflix boost from Stranger Things. D&D didn\'t just create tabletop roleplaying. Its DNA is embedded in virtually every RPG video game ever made, from Final Fantasy to Baldur\'s Gate to Skyrim.' as string | undefined, popupImage: dndNewImg as string | null },
  { name: 'Lemonade Stand', year: '1979', image: lemonadeImg as string | null, description: 'Lemonade Stand is one of the earliest business simulation video games ever made. Originally written in BASIC by Bob Jamison for the Minnesota Educational Computing Consortium (MECC), the same organization behind The Oregon Trail, it first appeared on Apple II computers in 1979 and became a staple of school computer labs throughout the 1980s.\n\nThe premise was beautifully simple: you run a lemonade stand. Each day you decide how many cups of lemonade to make, how much to charge, and how many advertising signs to buy, all while contending with randomly generated weather conditions. Sunny days meant booming sales; thunderstorms meant financial ruin and unsold inventory.\n\nIt taught basic economics (supply and demand, risk assessment, profit margins) without ever feeling like a lesson. The game was distributed on MECC\'s compilations alongside other educational software, making it one of the most widely played early computer games in American schools. Its influence echoes through every tycoon and management sim that followed.\n\nThe concept has been remade and reimagined countless times, on web browsers, mobile apps, and modern platforms, but the core loop of "guess the weather, set your price, pray you don\'t go bankrupt" remains timeless.' as string | undefined, popupImage: lemonadeImg as string | null },
  { name: 'Sierra Entertainment', year: '1979–present', image: sierraImg as string | null, description: 'Sierra On-Line (later Sierra Entertainment) was founded in 1979 by husband-and-wife team Ken and Roberta Williams in Simi Valley, California (later relocated to Oakhurst, a tiny town in the Sierra Nevada foothills). Roberta had become fascinated with the text adventure game "Colossal Cave Adventure" and wondered: what if an adventure game had pictures? She designed **Mystery House** (1980), widely considered the first graphic adventure game, and Ken programmed it for the Apple II. They sold it from their kitchen table and it became a hit.\n\nFrom there, Sierra became one of the most important game studios in history, defining the adventure game genre and pioneering narrative-driven gaming. Their catalog is legendary:\n\n**King\'s Quest** (1984-1998): Roberta Williams\' flagship series, the first animated graphic adventure game, following the royal family of Daventry through fairy-tale landscapes.\n**Space Quest** (1986-1995): A comedic sci-fi adventure series created by the "Two Guys from Andromeda" (Mark Crowe and Scott Murphy), starring lovable space janitor Roger Wilco.\n**Leisure Suit Larry** (1987-2009): Al Lowe\'s raunchy, bumbling romantic comedy series that pushed boundaries and age-verification screens.\n**Police Quest** (1987-1998): Designed by real LAPD officer Jim Walls, a serious police procedural adventure.\n**Quest for Glory** (1989-1998): A groundbreaking RPG-adventure hybrid.\n**Gabriel Knight** (1993-1999): Jane Jensen\'s dark supernatural thriller series.\n**Phantasmagoria** (1995): A horror FMV game that was one of the most expensive productions of its era.\n\nSierra also published seminal non-adventure titles: **Half-Life** (1998), **Homeworld** (1999), and the early Lord of the Rings games.\n\nSierra had a golden era from the mid-1980s through the mid-1990s, but after being acquired by CUC International (1996), which merged into Cendant and then Vivendi, the company went through corporate turmoil. Studios were shuttered, beloved series were cancelled, and the Williams\' creative vision was replaced by corporate management. Activision acquired Vivendi Games (including Sierra) in 2008. The Sierra brand was briefly revived in 2014 under Activision as a publishing label for indie games before going dormant again.' as string | undefined, popupImage: sierraImg as string | null },
  { name: 'Theatrix Interactive', year: '1982–1997', image: theatrixImg as string | null, description: 'Theatrix Interactive was founded in 1982 by Joyce Hakansson in Berkeley, California, originally under the name Berkeley Learning Technologies. Hakansson\'s ambition from day one was to create educational software, and over the next decade her company quietly became one of the most prolific behind-the-scenes forces in children\'s edutainment, creating more than 50 children\'s products for other publishers, including Edmark, Broderbund, and Davidson & Associates.\n\nThis is the hidden origin story that connects so many beloved 1990s educational games: Hakansson\'s team was the one who actually developed **Millie\'s Math House** and **Bailey\'s Book House**, which were then published under the Edmark brand. They also created **The Cruncher** for Davidson. Beyond software, the company designed and produced titles for electronic learning toy companies including Sega, Texas Instruments, and Tiger Electronics.\n\nIn May 1995, Hakansson rebranded the company as Theatrix Interactive, Inc. and stepped into publishing their own titles for the first time. Under this new identity, they released **Theatrix\'s Hollywood**, a creative moviemaking game where kids could direct, cast, and produce their own animated films using drag-and-drop tools. **Hollywood High** followed, bringing the concept to a teen-oriented setting. **Bumptz Science Carnival** taught science concepts through carnival-themed experiments. **Snootz Math Trek** turned math into a space adventure. And their crown jewel collaboration was the **Juilliard Music Adventure** (1995), created in partnership with The Juilliard School.\n\nOn August 12, 1997, Sanctuary Woods acquired 100% of Theatrix\'s outstanding shares, absorbing the company. Theatrix represents a pattern common in 1990s edutainment: the most impactful creative work was often done by small, passionate studios whose names never appeared on the box. Hakansson\'s team shaped how an entire generation learned to read, count, and think. They just did it under everyone else\'s logo until they finally got their own.' as string | undefined, popupImage: theatrixImg as string | null },
  { name: 'The Oregon Trail', year: '1985', image: oregonTrailImg as string | null, description: 'The Oregon Trail is the most famous educational video game ever made. It was originally created in 1971 by three student teachers in Minnesota, Don Rawitsch, Bill Heinemann, and Paul Dillenberger, who programmed it in BASIC on a teletype terminal (no screen, just a printer) over two weeks to teach Rawitsch\'s 8th-grade history class about 19th-century pioneer life. After the class ended, Rawitsch saved the code on a paper tape roll and shelved it.\n\nIn 1974, he joined MECC (Minnesota Educational Computing Consortium), which distributed software to schools statewide, and resurrected the program. The version most people remember is the 1985 Apple II edition, which added graphics, hunting minigames, and the iconic green-and-black screen.\n\nPlayers led a family of settlers from Independence, Missouri to Oregon\'s Willamette Valley, making decisions about supplies, river crossings, hunting, and pace, while contending with dysentery, broken wagon axles, snakebites, cholera, and exhaustion. "You have died of dysentery" became one of gaming\'s first memes, decades before that word existed.\n\nMECC released updated versions throughout the 1990s (1992, 1993, 1997, 2001) with improved graphics and expanded content. The game has been estimated to have been played by over 65 million people, teaching generations of American schoolchildren that the frontier was beautiful, terrifying, and full of dead oxen.' as string | undefined, popupImage: oregonTrailImg as string | null },
  { name: 'Edmark Games', year: '1986–1999', image: edmarkImg as string | null, description: 'Edmark Corporation was founded in 1970 by Gordon B. Bleil in Redmond, Washington, originally as a publisher of print educational materials for special-needs students. The company\'s roots trace to research at the University of Washington\'s Child Development center, where B.F. Skinner\'s operant conditioning theories were applied to develop reading programs for people with severe mental disabilities, groundbreaking work that proved for the first time that reading could be taught to this population.\n\nFor its first two decades, Edmark was a modest operation with annual sales under $1 million. Everything changed in the late 1980s when CEO Sally Narodick steered the company toward multimedia educational software, hiring educator and developer Donna Stanger in 1991 to lead product development. The result was a golden age of children\'s educational software that defined the genre:\n\n**Millie\'s Math House** (1992): Starring Millie the cow, teaching counting, shapes, and patterns through delightful interactive activities.\n**Bailey\'s Book House** (1993): Bailey the cat guiding kids through reading, phonics, and word play.\n**KidDesk** (1993): A child-friendly desktop replacement that kept kids out of your actual files.\n**Sammy\'s Science House** (1994): Sammy the snake introducing observation, sorting, and experimentation.\n**Thinkin\' Things Collection 1, 2, & 3** (1993-1995): Creative thinking games featuring memorable characters like Fripple.\n**Trudy\'s Time and Place House** (1995): Geography and time concepts.\n**Stanley\'s Sticker Stories** (1996): Open-ended digital storytelling.\n**Strategy Games of the World** (1995): Mancala, Nine Men\'s Morris, and Go-Moku with history lessons.\n**The Logical Journey of the Zoombinis** (1996): A cult-classic logic puzzle game about guiding blue blob creatures to freedom.\n\nEdmark won over 340 industry design awards. IBM acquired the company for $102.3 million in 1996, then sold it to Riverdeep Interactive Learning for $85 million in 2000. The brand went defunct by the mid-2000s. For kids who grew up in the 1990s, Edmark games were the gold standard: software that was genuinely fun without ever making you feel like you were being taught.' as string | undefined, popupImage: edmarkImg as string | null },
  { name: 'Zelda Series', year: '1986–present', image: zeldaImg as string | null, description: 'The Legend of Zelda debuted on February 21, 1986 on the Famicom Disk System in Japan, designed by Shigeru Miyamoto and Takashi Tezuka at Nintendo. Miyamoto drew inspiration from his childhood exploring the countryside around Kyoto, wandering into caves, discovering hidden lakes, getting lost in forests. He wanted to recreate that sense of wonder and exploration in a game.\n\nThe original game dropped players into the land of Hyrule with almost no instructions and asked them to figure everything out: find the dungeons, collect the Triforce pieces, defeat Ganon, rescue Princess Zelda. It was revolutionary. An open world you could explore in any order, a battery-backed save system (a first for console games), and a sense of mystery that rewarded curiosity.\n\nThe series evolved through landmark entries: **A Link to the Past** (1991, SNES) perfected the formula; **Ocarina of Time** (1998, N64) brought it into 3D and is regularly cited as one of the greatest games ever made; **Majora\'s Mask** (2000) was its dark, time-looping companion; **The Wind Waker** (2002) divided fans with its cel-shaded art (later universally beloved); **Twilight Princess** (2006) went darker; **Breath of the Wild** (2017) reinvented the entire open-world genre and sold over 30 million copies; **Tears of the Kingdom** (2023) expanded on it with physics-based building mechanics.\n\nThe naming is a deliberate subversion: the series is named for the princess, but you always play as Link. Miyamoto named Zelda after Zelda Fitzgerald, F. Scott Fitzgerald\'s wife, because he thought the name sounded "pleasant and significant."' as string | undefined, popupImage: zeldaImg as string | null },
  { name: 'Mavis Beacon Teaches Typing', year: '1987', image: mavisBeaconImg as string | null, description: 'Mavis Beacon Teaches Typing, released in 1987 by The Software Toolworks, has one of the strangest origin stories in software history: Mavis Beacon is not a real person. She was invented.\n\nThe software\'s creators, Les Crane (a former TV talk show host turned tech entrepreneur) and Walt Bilofsky, needed a spokesperson and chose the name "Mavis" from a songbird and "Beacon" as a guiding light. The woman on the cover of the original box was actually a Caribbean-born retail worker named Renée L\'Espérance, spotted by a marketing scout in a department store who thought she had the right look: warm, professional, trustworthy. She was paid a one-time modeling fee and had no ongoing connection to the product.\n\nDespite being entirely fictional, Mavis Beacon became one of the most recognizable names in educational software, teaching millions of people to touch-type through exercises that tracked speed and accuracy, adapting difficulty to the learner. The software went through numerous versions across decades, surviving multiple publisher changes.\n\nAt one point, it was estimated that Mavis Beacon had taught more people to type than any human teacher in history. The brand endured well into the 2010s, making a fictional woman one of the longest-running "instructors" in computing.' as string | undefined, popupImage: mavisBeaconImg as string | null },
  { name: 'MadMaze', year: '1989', image: madmazeImg as string | null, description: 'MadMaze holds a unique distinction in gaming history: it was the first online game to attract over a million players. Designed by Eric Goldberg and developed by Greg Costikyan, both veterans of tabletop RPG design who had previously collaborated on the cult classic game "Paranoia," MadMaze launched in 1989 on the Prodigy online service, a pre-Internet dial-up platform jointly operated by IBM and Sears.\n\nThe game used Prodigy\'s NAPLPS vector graphics protocol to render colorful but simple first-person corridor views as you navigated a sprawling labyrinth. You played a boy from the rural community of Weith Village, sent by the Village Elder to travel through the MadMaze and recruit a wizard named Moraziel to defeat "The Mad One," an insane deity of primal chaos whose maze threatened to engulf your home.\n\nBetween the mazes were "Places of Power," interactive narrative scenes with logic puzzles, riddles, and branching choices, some leading to gruesome deaths. It had multiple endings, including one where you become the Mad One\'s minion forever.\n\nFor families paying by-the-minute for Prodigy access, MadMaze was often the single biggest draw of the service. Kids and adults alike would carefully map out mazes on graph paper to avoid wasting precious connection time.\n\nWhen Prodigy shut down in 1999, MadMaze vanished with it. Fan Russell Brown created a web recreation called "MadMaze-II" in 2001, and after Brown\'s passing, the game was preserved on the Vintage Computing website. Even Costikyan himself was critical of his creation, calling it a solitary experience that wasted the potential of a networked platform. But for over a million people in the early 1990s, it was their first taste of online gaming.' as string | undefined, popupImage: madmazeImg as string | null },
  { name: 'Lemmings', year: '1991', image: lemmingsImg as string | null, description: 'Lemmings was created by DMA Design in Dundee, Scotland, the same studio that would later become Rockstar North and create Grand Theft Auto. The game\'s concept came from a tiny animation: programmer Mike Dailly created an 8x8 pixel character walking across the screen as a joke, and the team realized the little guy was hilarious and oddly compelling.\n\nThe premise: mindless green-haired lemmings march single-file out of a trapdoor and walk directly into hazards, off cliffs, into lava, under crushers. Your job is to assign skills to individual lemmings (digger, climber, builder, blocker, bomber, and more) to guide enough of them safely to the exit. It\'s a puzzle game dressed as a catastrophe.\n\nThe soundtrack was a huge part of what made Lemmings so memorable, a mix of playful arrangements of public domain classics like the Can-Can, Pachelbel\'s Canon, and "She\'ll Be Comin\' Round the Mountain," alongside original compositions by Tim Wright (later known as CoLD SToRAGE, the legendary composer behind the Wipeout and Colony Wars soundtracks).\n\nPublished by Psygnosis in 1991, Lemmings was an immediate smash hit, eventually ported to over 20 different systems. It was the best-selling game on the Amiga, with 55,000 copies sold on its first day alone, and an estimated 15 million copies sold across all platforms by 2006.' as string | undefined, popupImage: lemmingsImg as string | null },
  { name: 'MindTrap', year: '1991', image: mindtrapImg as string | null, description: 'MindTrap is a lateral-thinking puzzle card game created by Richard Fast in 1991 in Canada. It arrived at the intersection of the trivia game craze (kicked off by Trivial Pursuit in 1981) and a growing appetite for brain teasers and logic puzzles.\n\nThe game presents players with short scenarios: murder mysteries, logic riddles, word puzzles, and trick questions that require creative thinking rather than factual knowledge. A typical MindTrap question sets up a seemingly impossible situation and asks you to figure out what really happened, often hinging on assumptions you didn\'t realize you were making.\n\nIt became a cult hit at dinner parties and family game nights throughout the 1990s, with multiple editions released over the years. The game was published by Outset Media and sold millions of copies. It carved out a niche distinct from both trivia games and traditional board games. You didn\'t need to know anything, you just needed to think differently.' as string | undefined, popupImage: mindtrapImg as string | null },
  { name: 'Sonic the Hedgehog', year: '1991–present', image: sonicImg as string | null, description: 'Sonic the Hedgehog was born out of corporate war. In 1990, Sega president Hayao Nakayama ordered his developers to create a mascot that could dethrone Nintendo\'s Mario. An internal contest produced hundreds of submissions. The winner came from artist Naoto Ohshima: a blue hedgehog. Ohshima tested his sketches by polling random strangers in Central Park, New York. The hedgehog won. Its blue color matched Sega\'s cobalt logo. Its red and white shoes were inspired by Michael Jackson\'s boots on the cover of "Bad" combined with Santa Claus\'s color scheme. Its personality was modeled on Bill Clinton\'s "can-do" attitude (then Governor of Arkansas). The character was originally codenamed "Mr. Needlemouse," a literal translation of the Japanese word for hedgehog (harinezumi).\n\nProgrammer Yuji Naka built the engine around a novel algorithm that let sprites move smoothly along curves, enabling Sonic to roll through loops at speeds no platformer had achieved. Naka was a Mario fan but was frustrated that getting better at Mario didn\'t let you go faster. He wanted a game where skill was rewarded with speed. The soundtrack was composed by Masato Nakamura, bassist of the J-pop band Dreams Come True.\n\nThe original launched June 23, 1991, developed by just seven people who named themselves "Sonic Team." It sold over 15 million copies on Genesis alone, giving Sega 65% market share against Nintendo in North America. Sonic 2 (1992) introduced Tails (Miles "Tails" Prower, yes, "miles per hour"), a two-tailed fox. Sonic 3, Sonic & Knuckles (1994), Sonic Adventure (1998), and dozens more followed, ranging from beloved (Sonic Mania, 2017) to notorious (Sonic 2006). The films starring Ben Schwartz and Jim Carrey became surprise box office hits.\n\nSonic also spawned a massive comic book universe. Archie Comics published Sonic the Hedgehog from 1993 to 2017, running 290 issues, the longest-running video game comic and longest-running licensed comic series ever.\n\nA fun connection: Naoto Ohshima, who designed Sonic, later left Sega and directed Alundra (1997), another game on this list.' as string | undefined, popupImage: sonicImg as string | null },
  { name: 'Tornado Rex', year: '1991', image: tornadoRexImg as string | null, description: 'Tornado Rex was made by Parker Brothers in 1991 and is one of the more gloriously absurd board games of the era. It featured a massive 3D plastic mountain that you assembled from two pieces, with a winding trail spiraling from base camp to the summit. Players raced their little hiker pieces up the mountain by drawing cards.\n\nBut lurking at the top was Tornado Rex, a wind-up spinning top shaped like a vaguely dinosaur-like creature. When a player drew a Rex card, you wound up the beast and released it. It would careen down the mountain path, spinning wildly and knocking any hikers it hit off the trail or tumbling down the slope. It was pure chaos: part board game, part physics experiment.\n\nIts oversized box and fragile 3D board made it difficult to store and keep intact, which is why complete copies in good condition now command surprisingly high prices among collectors. It was a commercial underperformer. Warehouses full of unsold copies were reportedly destroyed, making surviving copies genuinely rare.' as string | undefined, popupImage: tornadoRexImg as string | null },
  { name: 'JumpStart Series', year: '1991–2009', image: jumpstartImg as string | null, description: 'The JumpStart series was created by Knowledge Adventure, an educational software company founded in 1991 by Bill Gross in Glendale, California. The first JumpStart title, **JumpStart Kindergarten**, was released in 1994 and established the formula: grade-specific educational games covering reading, math, science, and critical thinking, wrapped in colorful adventures with recurring characters.\n\nThe series expanded rapidly through the mid-to-late 1990s: **JumpStart 1st Grade** (1995), **JumpStart 2nd Grade** (1996), **JumpStart Adventures 3rd Grade: Mystery Mountain** (1996, widely considered the series\' masterpiece), **JumpStart 4th Grade: Haunted Island** (1996), and preschool/kindergarten entries.\n\nThe series was notable for increasing production values through the late 1990s, with fully animated cutscenes, voice acting, and genuinely engaging gameplay loops. Knowledge Adventure went through several ownership changes, acquired by Cendant in 1997, then Vivendi, then eventually NetDragon Websoft.\n\nAt its peak, JumpStart was one of the most successful educational game franchises in the world, with over 40 titles and millions of copies sold.' as string | undefined, popupImage: jumpstartImg as string | null },
  { name: 'Kirby\'s Dream Land', year: '1992', image: kirbyImg as string | null, description: 'Kirby\'s Dream Land was released for the Game Boy on April 27, 1992, in Japan, and was designed by a 19-year-old Masahiro Sakurai at HAL Laboratory. Sakurai, who had joined HAL straight out of high school, was given the task of creating a game that would be accessible to beginners.\n\nThe character that became Kirby started as a simple placeholder blob in the prototype, a round, featureless shape that Sakurai drew as a stand-in while developing the gameplay. The team grew so attached to the little blob that they kept him. Sakurai wanted the character to be white; Shigeru Miyamoto suggested yellow. Nintendo of America\'s marketing team pushed for pink. Pink won, though since the game was on the original Game Boy\'s monochrome screen, most Western players didn\'t know Kirby was pink until later.\n\nThe name "Kirby" is widely believed to be a tribute to John Kirby, the lawyer who successfully defended Nintendo in the Universal Studios v. Nintendo lawsuit over Donkey Kong.\n\nThe game itself was intentionally short and easy, beatable in under 30 minutes, because Sakurai designed it as a gateway game. But it introduced Kirby\'s signature ability to inhale enemies and float by puffing up with air. The iconic copy ability didn\'t actually appear until the sequel, Kirby\'s Adventure (1993) on NES. From there, Kirby became one of Nintendo\'s most enduring franchises. Sakurai would go on to create Super Smash Bros., but Kirby, that little pink placeholder blob he drew at 19, remains his first and most personal creation.' as string | undefined, popupImage: kirbyImg as string | null },
  
  { name: 'Magic: The Gathering', year: '1993', image: magicImg as string | null, description: 'Magic: The Gathering was created by mathematician Richard Garfield and published by Wizards of the Coast in 1993. Garfield was a math PhD candidate at the University of Pennsylvania who had pitched a board game to Peter Adkison, founder of the tiny game company Wizards of the Coast. Adkison liked Garfield but said the board game was too expensive to produce. Did he have something cheaper?\n\nGarfield went home and designed a game using cards that could be printed inexpensively. His stroke of genius was the idea that each player would buy their own random assortment of cards and build a personalized deck, meaning no two players would have the same experience. This "collectible card game" model had never been done before.\n\nThe first print run (Alpha) sold out immediately at Gen Con in August 1993. Then the next print run (Beta) sold out. Then Unlimited. The game became a cultural and financial juggernaut, creating an entirely new product category.\n\nIt spawned thousands of imitators, a Pro Tour competitive circuit with millions in prizes, a thriving secondary market where individual rare cards sell for tens of thousands of dollars (a Black Lotus Alpha card sold for over $500,000), and expansions released multiple times per year for over 30 years. Wizards of the Coast used the profits from Magic to purchase TSR and the rights to Dungeons & Dragons in 1997, and Hasbro then acquired Wizards in 1999. As of the 2020s, Magic has printed over 25,000 unique cards and remains the best-selling trading card game in the world.' as string | undefined, popupImage: magicImg as string | null },
  { name: 'Myst Series', year: '1993–2005', image: mystImg as string | null, description: 'Myst was created by brothers Rand and Robyn Miller at their tiny studio Cyan, Inc. in Spokane, Washington. Before Myst, they had made children\'s educational games ("The Manhole," "Cosmic Osmo") using HyperCard on Macintosh. When they decided to make a game for adults, they drew on their shared love of Jules Verne, solitary exploration, and mysterious places.\n\nMyst (1993) dropped players onto a hauntingly beautiful island with no instructions, no enemies, no time pressure, and no dialogue, just strange mechanical puzzles embedded in the environment and cryptic books that transported you to different "Ages." The game was rendered entirely in pre-rendered 3D stills. You clicked to move between static viewpoints, which gave it an eerie, photographic quality unlike anything else at the time.\n\nMyst became the best-selling PC game of all time (until The Sims surpassed it in 2002), moving over 6 million copies and single-handedly driving CD-ROM adoption. It proved that games could be contemplative, atmospheric, and commercially successful without violence.\n\nThe series continued with Riven (1997), the Millers\' masterwork, a staggeringly detailed and difficult sequel set across five interconnected islands. Myst III: Exile (2001) and Myst IV: Revelation (2004) were developed by other studios. Myst V: End of Ages (2005) returned to Cyan and concluded the saga. Rand Miller has continued developing at Cyan, releasing Obduction (2016) and Firmament (2023) as spiritual successors.' as string | undefined, popupImage: mystImg as string | null },
  
  { name: 'Jumanji', year: '1995', image: jumanjiImg as string | null, description: 'The Jumanji board game was released by Milton Bradley in 1995 as a tie-in to the blockbuster Robin Williams film, which itself was adapted from Chris Van Allsburg\'s 1981 picture book of the same name.\n\nVan Allsburg, a Caldecott Medal-winning illustrator known for "The Polar Express," created the original story about two children who discover a mysterious board game that manifests real jungle dangers in their home with every roll of the dice. The picture book was sparse and haunting, with Van Allsburg\'s signature chiaroscuro illustrations lending it a dreamlike menace.\n\nThe 1995 film, directed by Joe Johnston and starring Robin Williams, expanded the story into a full adventure where Williams\' character had been trapped inside the game for 26 years. The tie-in board game attempted to capture the film\'s chaos. Players rolled dice and drew "danger cards" describing jungle hazards while racing to reach the center and yell "JUMANJI!" to end the game.\n\nThe Jumanji franchise was revived with "Jumanji: Welcome to the Jungle" (2017) and "Jumanji: The Next Level" (2019), both starring Dwayne Johnson, which reimagined the concept as a video game rather than a board game.' as string | undefined, popupImage: jumanjiImg as string | null },
  { name: 'Crash Bandicoot', year: '1996', image: crashBandicootImg as string | null, description: 'Crash Bandicoot was developed by Naughty Dog and published by Sony Computer Entertainment for the PlayStation in 1996. The game was the brainchild of Andy Gavin and Jason Rubin, two childhood friends who had been making games together since they were teenagers on Apple II computers.\n\nWhen Sony launched the PlayStation, Naughty Dog saw an opportunity to create a character-driven 3D platformer that could serve as Sony\'s answer to Mario and Sonic. Internally, the project was codenamed "Sonic\'s Ass Game" because the camera sat behind the character as he ran into the screen, meaning you spent the whole game staring at his backside.\n\nThe character went through many designs before settling on a bandicoot, an Australian marsupial chosen partly because it was obscure enough that nobody had strong preconceptions about what one should look like. Naughty Dog pushed the PlayStation hardware harder than almost anyone at the time, developing custom rendering techniques.\n\nThe original trilogy plus Crash Team Racing (1999) were all developed by Naughty Dog and are considered the definitive entries. After Naughty Dog moved on to Jak and Daxter (and eventually The Last of Us and Uncharted), the franchise passed through multiple developers. Activision released the Crash Bandicoot N. Sane Trilogy remaster (2017), which was a massive hit, followed by Crash Bandicoot 4: It\'s About Time (2020).' as string | undefined, popupImage: crashBandicootImg as string | null },
  { name: 'Pokémon', year: '1996', image: pokemonImg as string | null, description: 'Pokémon was created by Satoshi Tajiri and programmed by his friend Shigeki Morimoto at the studio Game Freak, published by Nintendo. Tajiri was an insect-collecting enthusiast as a child in suburban Tokyo, and as Japan\'s rice paddies and forests were paved over during rapid urbanization, he wanted to recreate the joy of discovering and collecting creatures for a generation of kids who would never have that experience.\n\nDevelopment of the original Game Boy games took six years, from 1990 to 1996, during which Game Freak nearly went bankrupt multiple times. Tajiri worked without pay, and several employees quit. Even Nintendo had low expectations; the Game Boy was considered a dying platform by 1996.\n\nPokémon Red and Green launched in Japan on February 27, 1996 and sold modestly at first, but word of mouth, particularly around the link cable trading feature, which Tajiri considered the game\'s core innovation, turned it into a phenomenon. The concept of needing to trade with friends to complete your collection ("Gotta Catch \'Em All") was Tajiri\'s masterstroke, inspired by the Game Boy\'s link cable, which he imagined as insects crawling between devices.\n\nBy the time Red and Blue hit the West in 1998, it was a cultural tsunami. Pokémon has since sold over 480 million video games, making it one of the highest-grossing media franchises in history (over $100 billion total).' as string | undefined, popupImage: pokemonImg as string | null },
  
  { name: 'Alundra', year: '1997', image: alundraImg as string | null, description: 'Alundra was developed by Matrix Software and published by Working Designs for the PlayStation in 1997. It\'s an action-RPG in the tradition of 2D Zelda games, but with a significantly darker tone and more punishing difficulty.\n\nYou play as Alundra, a young "Dreamwalker" with the ability to enter people\'s dreams and nightmares. Shipwrecked in the village of Inoa, Alundra discovers the villagers are plagued by recurring nightmares that are literally killing them, and he must enter their subconscious minds to battle the demons within.\n\nThe game was directed by Naoto Ohshima, who had previously designed Sonic the Hedgehog\'s character at Sega. What set Alundra apart was its willingness to go dark. Characters you care about die, and you can\'t save everyone. The dream sequences were surreal and unsettling, the puzzles were notoriously difficult, and the story dealt with themes of faith, grief, and the existence of God.\n\nWorking Designs\' localization, led by Victor Ireland, was praised for its sharp, literate translation. The original remains a cult classic among PlayStation-era RPG fans.' as string | undefined, popupImage: alundraImg as string | null },
  { name: 'Legend of Legaia', year: '1998', image: legendOfLegaiaImg as string | null, description: 'Legend of Legaia was developed by Prokion (later Contrail) and published by Sony Computer Entertainment for the PlayStation in 1998. Set in a world consumed by a poisonous supernatural fog called the Mist, which turns creatures called Seru into violent monsters and enslaves humans who wear them, the game follows Vahn, a young man from the isolated village of Rim Elm.\n\nThe game\'s standout feature was its "Tactical Arts System," a unique combat mechanic where instead of selecting "Attack" from a menu, you input directional combos (Up, Down, Left, Right) to chain together martial arts moves, discovering hidden "Arts" combos through experimentation. It felt like a fighting game embedded inside a JRPG.\n\nThe Seru themselves could be absorbed and summoned in battle, functioning somewhat like Pokémon within a more traditional RPG framework. Despite mixed critical reception at the time, Legend of Legaia developed a dedicated cult following for its creative combat system, moody atmosphere, and surprisingly emotional story.' as string | undefined, popupImage: legendOfLegaiaImg as string | null },
  { name: 'Game Boy Camera', year: '1998', image: gameboyCameraImg as string | null, objectPosition: 'center top', description: 'The Game Boy Camera, released in 1998, was Nintendo\'s gloriously weird peripheral that turned the humble Game Boy into a 128x112 pixel digital camera with a 2-bit color palette (four shades of gray-green). It held the Guinness World Record for the smallest digital camera at the time of release.\n\nIt took grainy, pixelated, ghostly photos that looked like surveillance footage from a dream, and that\'s exactly what made it magical. Beyond just taking photos, it included a suite of bizarre mini-games, a music sequencer, a stamp editor for decorating your photos, and deeply strange animated sequences that bordered on surreal art. Photos could be printed using the Game Boy Printer, a thermal printer accessory that produced tiny sticker-sized printouts.\n\nThe camera\'s aesthetic, low-res, dithered, accidentally artistic, has experienced a significant revival in the 2020s, with artists and photographers deliberately using Game Boy Cameras for their unique look. The device has been modified by hardware enthusiasts to interface with modern printers and computers.\n\nIt was a product ahead of its time in concept (a portable camera for self-expression and play) but limited by 1998 technology, making it a charming artifact of Nintendo\'s "let\'s try something weird" philosophy.' as string | undefined, popupImage: gameboyCameraImg as string | null },
  { name: 'Spyro', year: '1998', image: spyroImg as string | null, description: 'Spyro the Dragon was created by Insomniac Games and published by Sony Computer Entertainment for the PlayStation in 1998. The team used a custom "Level of Detail" system that could render vast draw distances, unusual for PS1 games, which typically hid their limitations with fog. The result was a game where you could stand on a hilltop and see the entire level spread out below you.\n\nComposer Stewart Copeland of The Police wrote the soundtrack, giving the game a distinctive percussive energy. The original trilogy, Spyro the Dragon (1998), Spyro 2: Ripto\'s Rage! (1999), and Spyro: Year of the Dragon (2000), were all developed by Insomniac and are considered the definitive entries.\n\nAfter Insomniac moved on to Ratchet & Clank, Spyro passed through several developers with diminishing results until the "Skylanders" franchise repurposed the character for a toys-to-life game series (2011). In 2018, all three original games were beautifully remastered as the "Spyro Reignited Trilogy" by Toys for Bob.' as string | undefined, popupImage: spyroImg as string | null },
  { name: 'Dance Dance Revolution', year: '1998', image: ddrImg as string | null, description: 'Dance Dance Revolution (DDR) was created by Konami and debuted in Japanese arcades in November 1998. DDR placed players on a metal dance pad with four directional arrows and asked them to step on the correct arrows in time with scrolling on-screen prompts synced to high-energy J-pop, eurobeat, and electronic music. The concept was simple, the execution was physically demanding, and the result was electrifying.\n\nArcade DDR cabinets became cultural gathering points in Japan and then worldwide, with skilled players performing elaborate freestyle routines that drew crowds. Home console versions followed for PlayStation (1999 onward), with soft foam pads that brought the experience to living rooms everywhere.\n\nDDR spawned an entire rhythm-game movement, influencing Guitar Hero, Rock Band, Beat Saber, and the broader genre. It was also one of the first video games studied for health benefits. Schools and fitness programs adopted it, and studies showed it could genuinely improve cardiovascular fitness. Konami continued releasing DDR iterations for over two decades, with the arcade franchise still active in Japan.' as string | undefined, popupImage: ddrImg as string | null },
  { name: 'MTV Music Generator', year: '1999', image: mtvMusicImg as string | null, description: 'MTV Music Generator (known as Music 2000 in Europe) was a music sequencer developed by Jester Interactive and published by Codemasters for the PlayStation in 1999. It was the sequel to 1998\'s "Music: Music Creation for the PlayStation," which had been the first non-game utility Sony ever allowed on the PlayStation.\n\nJester Interactive was founded in 1997 in North Wales by Tim Wright (the same Tim Wright, aka CoLD SToRAGE, who composed replacement tracks for Lemmings and created the Wipeout and Colony Wars soundtracks at Psygnosis), his brother Lee Wright, and Gavin Morgan. After leaving Psygnosis in 1997, Tim Wright wanted to bring music creation tools to home consoles, democratizing beat-making for teenagers who couldn\'t afford professional studio equipment.\n\nThe game provided 24 channels, approximately 4,500 samples spanning techno, jungle, house, drum and bass, and rock, a built-in CD sampler, and a visual block-based editor where you stacked color-coded bars for beats, melodies, basslines, and effects. It won Official PlayStation Magazine\'s Most Innovative Game 1999 and was twice BAFTA-nominated.\n\nWhat made it culturally significant was its role as a gateway for future music producers. Most famously, Sounwave, the in-house producer for Top Dawg Entertainment (Kendrick Lamar\'s label), made his first beats on MTV Music Generator. From a PS1 music game to producing Grammy-winning albums.\n\nThe series continued through PS2 and Xbox versions before PC-based DAWs like FL Studio overtook the concept. Over 25 years later, a dedicated community still makes music with the original PS1 version, and the sample library has been archived online.' as string | undefined, popupImage: mtvMusicImg as string | null },
  { name: 'RollerCoaster Tycoon', year: '1999', image: rollerCoasterImg as string | null, description: 'RollerCoaster Tycoon was developed almost entirely by one person: Chris Sawyer, a Scottish programmer who hand-coded the game in assembly language, a painstaking, low-level programming language that most developers had abandoned in favor of higher-level tools by the late 1990s.\n\nPublished by MicroProse in 1999, RCT put players in charge of designing and managing a theme park: building roller coasters track-piece by track-piece, managing staff, setting prices, landscaping terrain, and keeping guests happy. The coaster designer was the star. Players could create elaborate custom rides and then watch simulated guests ride them, sometimes throwing up afterward if the G-forces were too intense.\n\nThe game sold over 4 million copies and was one of the best-selling PC games of the late 1990s. Sequels followed: RollerCoaster Tycoon 2 (2002, also largely coded by Sawyer in assembly) and RollerCoaster Tycoon 3 (2004, by Frontier Developments, which introduced 3D graphics and the ability to ride your own coasters in first person).\n\nThe franchise continued with mixed results through mobile games and RCT World (2016), while Frontier went on to create Planet Coaster (2016), widely considered the spiritual successor.' as string | undefined, popupImage: rollerCoasterImg as string | null },
  { name: 'Tony Hawk\'s Pro Skater', year: '1999', image: tonyHawkImg as string | null, description: 'Tony Hawk\'s Pro Skater was developed by Neversoft and published by Activision in 1999 for the PlayStation. The game emerged from a unique moment: skateboarding was experiencing a mainstream resurgence in the late 1990s, and Tony Hawk, already the most famous skater alive, had just landed the first-ever documented 900 at the 1999 X Games, months before the game\'s release.\n\nNeversoft, a small studio that had previously made only a forgettable Bruce Willis game, was given the skateboarding license and poured their enthusiasm into it. The game\'s genius was its accessible arcade-style control scheme (anyone could pull off a kickflip within seconds) combined with a deep combo system that rewarded skilled players who chained tricks together for massive scores.\n\nThe soundtrack, featuring Dead Kennedys, Goldfinger, Primus, and The Vandals, became iconic and introduced an entire generation to punk and ska.\n\nThe game sold millions and spawned a beloved series: THPS2 (2000, widely considered the pinnacle), THPS3 (2001), THPS4 (2002), and Tony Hawk\'s Underground (2003). Quality declined in later entries, and the franchise hit rock bottom with "Tony Hawk\'s Pro Skater 5" (2015). A redemption came with the critically acclaimed Tony Hawk\'s Pro Skater 1 + 2 remaster (2020) by Vicarious Visions.' as string | undefined, popupImage: tonyHawkImg as string | null },
  { name: 'The Sim Series', year: '1989–present', image: theSimsImg as string | null, description: 'The Sim franchise traces back to Will Wright\'s **SimCity** (1989), the genre-defining city builder published by Maxis that let players zone, build, and manage an entire metropolis. It was revolutionary: a "software toy" with no win condition, just the pleasure of watching a complex system respond to your decisions. SimCity spawned an entire lineage of simulation games under the "Sim" banner.\n\n**SimCity 2000** (1993) expanded the formula with isometric 3D views, underground utilities, and arcologies. **SimAnt** (1991) simulated an ant colony. **SimFarm** (1993) put you in charge of agricultural management. **Sim Town** (1995) was a kid-friendly version of SimCity designed for younger players. **SimCopter** (1996) let you fly a helicopter through your SimCity 2000 cities in 3D. **SimCity 3000** (1999) refined the city builder further with advisors and regional play.\n\nThen came Wright\'s most ambitious project. Initially called "Project X" and later "Dollhouse," EA executives were deeply skeptical, reportedly calling it "the game about going to the bathroom." Wright\'s inspiration was partly academic (the work of architect Christopher Alexander on environmental psychology) and partly personal (after losing his home in the 1991 Oakland firestorm, he became interested in how people rebuild their domestic lives).\n\n**The Sims** (2000) dropped players into suburban homes with simulated people ("Sims") who needed to eat, sleep, socialize, work, and use the toilet. There was no winning condition. You just... lived. You could build dream houses, pursue careers, fall in love, have children, or deliberately trap your Sims in rooms without doors and watch them suffer (a pastime so universal it became a cultural meme).\n\nThe game became the best-selling PC game of all time, eventually surpassing Myst. **The Sims 2** (2004) added genetics and aging. **The Sims 3** (2009) introduced an open neighborhood. **The Sims 4** (2014) refined the building tools. The series has sold over 200 million copies and generated billions in revenue. Wright\'s creation proved that a game about mundane domestic life could be one of the most successful entertainment products ever made.' as string | undefined, popupImage: theSimsImg as string | null },
  { name: 'Animal Crossing', year: '2001', image: animalCrossingImg as string | null, description: 'Animal Crossing was originally released for the Nintendo 64 in Japan on April 14, 2001, designed by Katsuya Eguchi and Hisashi Nogami at Nintendo EAD. The game was born from a deeply personal place: Eguchi had moved away from his hometown to work at Nintendo in Kyoto and reflected on the loneliness of leaving behind friends and community.\n\nAnimal Crossing runs on the console\'s internal clock in real time. Cherry blossoms bloom in spring, snow falls in winter, shops close at night, and if you don\'t play for a week, weeds overtake your town and villagers ask where you\'ve been. There are no enemies, no fail states, no urgency, just the gentle rhythm of catching bugs, fishing, decorating your house, writing letters to anthropomorphic animal neighbors, and paying off your mortgage to a capitalist tanuki named Tom Nook.\n\nThe series grew through Wild World (2005, DS), City Folk (2008, Wii), New Leaf (2012, 3DS), and New Horizons (2020, Switch), which launched during the COVID-19 pandemic lockdowns and became a global cultural phenomenon, selling over 44 million copies.\n\nFor millions of people stuck at home, Animal Crossing became their social space, their creative outlet, and their gentle escape.' as string | undefined, popupImage: animalCrossingImg as string | null },
  { name: 'Katamari Damacy', year: '2004', image: katamariImg as string | null, description: 'Katamari Damacy was created by Keita Takahashi, a sculptor-turned-game-designer at Namco, and released in 2004 for the PlayStation 2.\n\nThe premise is magnificently absurd: the King of All Cosmos, a towering, flamboyant, emotionally volatile celestial being in purple tights, has accidentally destroyed all the stars in the sky during a drunken bender. He sends his tiny son, the Prince (who is 5 centimeters tall), down to Earth with a magical sticky ball called a Katamari. You roll the Katamari over objects, which stick to it and make it grow, from thumbtacks and candy to cats and people to buildings and mountains and eventually islands.\n\nThe soundtrack, composed by Yu Miyake and a team of eclectic musicians, is one of the most joyful and bizarre game soundtracks ever made, mixing J-pop, bossa nova, electronic, and choral arrangements.\n\nTakahashi deliberately designed the game as a rejection of the gaming industry\'s obsession with graphical realism and military themes. Namco gave it a tiny budget and no marketing. It became a critical darling and cult hit. Takahashi himself grew ambivalent about sequels and left Namco to pursue other creative projects, including designing playgrounds.' as string | undefined, popupImage: katamariImg as string | null },
  { name: 'Assassin\'s Creed Series', year: '2007–present', image: assassinsCreedImg as string | null, description: 'Assassin\'s Creed was created by Patrice Desilets and his team at Ubisoft Montreal, released in 2007. The game began its life as a spin-off of the Prince of Persia franchise, initially called "Prince of Persia: Assassin," before Ubisoft decided the concept had grown far enough from the source material to become its own property.\n\nThe core conceit was a science-fiction framework: a modern-day bartender named Desmond Miles is kidnapped by a corporation and forced into a machine called the Animus, which lets him relive the genetic memories of his ancestors. The first game placed players in the shoes of Altair Ibn-La\'Ahad during the Third Crusade in 1191.\n\nAssassin\'s Creed II (2009), set in Renaissance Italy with charismatic protagonist Ezio Auditore, is widely considered the series\' peak. The franchise became Ubisoft\'s flagship, releasing major installments nearly every year across historical settings from the American Revolution to Ancient Egypt to the Viking Age.\n\nThe series has sold over 200 million copies. Its detailed historical recreations are so thorough that Ubisoft added "Discovery Tour" modes that remove gameplay and let you explore the worlds as interactive museums.' as string | undefined, popupImage: assassinsCreedImg as string | null },
  { name: 'Cards Against Humanity', year: '2011', image: cardsAgainstImg as string | null, description: 'Cards Against Humanity was created by a group of eight friends from Highland Park, Illinois, who originally designed it for a New Year\'s Eve party in 2009.\n\nThe game is essentially a crass version of Apples to Apples: one player draws a black card with a fill-in-the-blank prompt, and everyone else plays a white card with the funniest (or most horrible) answer. The humor is deliberately transgressive.\n\nIn 2011, the group launched a Kickstarter campaign asking for $4,000 to professionally print the game. They raised $15,570. The game then became one of Amazon\'s best-sellers without any traditional marketing, driven entirely by word of mouth and social media.\n\nWhat sets Cards Against Humanity apart is the team\'s punk-rock approach to business: they released the game under a Creative Commons license (anyone can download and print it for free), pulled elaborate stunts for Black Friday (selling nothing for $5, digging a pointless hole in the ground), and used profits for activism and comedy. The game has sold millions of copies, becoming a defining party game of the 2010s.' as string | undefined, popupImage: cardsAgainstImg as string | null },
  { name: '#IDARB', year: '2015', image: idarbImg as string | null, description: '#IDARB (an abbreviation of "It Draws a Red Box") is perhaps the most crowdsourced game ever made. In January 2014, Other Ocean Interactive developer Mike Mika tweeted a simple image of a red box standing on platforms and asked his followers what he should do with it.\n\nSuggestions flooded in. Game designer Brandon Sheffield replied with the key idea: add a ball and goals. Over the following weeks, development was driven by Twitter suggestions unified under the hashtag #IDARB (because the prototype literally just drew a red box).\n\nThe game evolved into a chaotic 2D multiplayer sports game: up to eight players, four per team, running and jumping across platforms trying to shoot a ball into the opposing team\'s goal. Its most innovative feature was "hashbombs." Viewers watching on Twitch or posting on Twitter could type hashtag commands that triggered in-game effects, warping the screen, changing gravity, or spawning objects. It was one of the earliest and most creative implementations of audience interaction in gaming.\n\nChris Charla, head of Microsoft\'s ID@Xbox program, saw the game\'s Twitter development and invited Mika to bring it to Xbox One. It launched in January 2015 as a free Games with Gold title.' as string | undefined, popupImage: idarbImg as string | null },
  { name: 'Red Dead Redemption II', year: '2018', image: redDeadImg as string | null, description: 'Red Dead Redemption II was developed by Rockstar Games and released in October 2018 after approximately eight years of development involving over 2,000 developers. It is a prequel to Red Dead Redemption (2010), set in 1899 during the dying days of the American Wild West.\n\nPlayers control Arthur Morgan, a senior member of the Van der Linde gang, a group of outlaws led by the charismatic Dutch van der Linde as they flee eastward across a fictionalized America after a botched robbery.\n\nThe game is staggering in its detail and ambition: horses\' testicles shrink in cold weather, Arthur\'s hair and beard grow in real time, NPCs have full daily routines, the ecosystem simulates predator-prey relationships, and you can spend hours just watching a sunset over the Heartlands.\n\nThe narrative is a slow-burn meditation on loyalty, change, and mortality. Arthur\'s story is ultimately a tragedy about a man reckoning with the consequences of a violent life. The game shipped over 50 million copies. RDR2 is frequently cited as one of the greatest video games ever made, praised for its writing, voice acting (particularly Roger Clark as Arthur Morgan), world-building, and emotional weight.' as string | undefined, popupImage: redDeadImg as string | null },
  { name: 'Apex Legends', year: '2019', image: apexImg as string | null, description: 'Apex Legends is the game that was secretly Titanfall 3, until it wasn\'t. Developed by Respawn Entertainment and published by Electronic Arts, Apex Legends launched on February 4, 2019, in one of the most audacious moves in gaming history: no prior marketing, no announcement, no buildup. Respawn simply revealed the game and released it the same day, for free.\n\nRespawn was founded by Vince Zampella and Jason West, former heads of Infinity Ward who had co-created Call of Duty and Modern Warfare before being fired by Activision in a messy contract dispute. Their Titanfall franchise (2014, 2016) was critically adored but commercially underperformed.\n\nAfter Titanfall 2 shipped, the team began prototyping Titanfall 3. Then PUBG happened. The battle royale phenomenon swept the industry, and Respawn\'s team built a prototype battle royale mode using Titanfall 3\'s classes and mechanics. It was immediately, undeniably fun. They kept it secret from EA for six months.\n\nThe critical design decisions were bold: no Titans, no wall-running, and mandatory three-person squads. Instead, Respawn focused on hero-based characters called "Legends" with unique abilities, and invented the revolutionary ping system, a single button that let players communicate tactically without voice chat. Apex hit 25 million players in its first week and 100 million within two years.' as string | undefined, popupImage: apexImg as string | null },
  { name: 'Untitled Goose Game', year: '2019', image: gooseImg as string | null, description: 'Untitled Goose Game was developed by House House, a four-person indie studio based in Melbourne, Australia. The game stars a horrible goose. That\'s it. That\'s the premise. You are a goose, and you are awful.\n\nSet in a sleepy English village, you waddle around honking, stealing things, scaring children, ruining picnics, trapping people in garages, and making a groundskeeper\'s life a living hell, all while consulting a to-do list of petty crimes.\n\nThe game emerged from a collaborative Slack conversation at House House where someone posted a stock photo of a goose, and the team joked about making a game about it. The humor is physical and situational. There\'s no dialogue, no cutscenes, just the escalating chaos of a single goose versus an entire village.\n\nComposer Dan Golding created a reactive score using Debussy\'s piano Preludes that dynamically shifts based on the goose\'s behavior: sneaking triggers quiet, tense passages; causing chaos triggers frantic crescendos. The game was published by Panic and launched in September 2019 to universal acclaim and viral internet fame. It won the D.I.C.E. Award for Outstanding Achievement in Character (for the goose), and sold over a million copies within three months. A free co-op update in 2020 added a second horrible goose, because one wasn\'t enough.' as string | undefined, popupImage: gooseImg as string | null },
];

/* Collections - commented out for now
const collections = [
  { name: 'Rocks', year: '1988', image: null as string | null },
  { name: 'Coins', year: '1989', image: null as string | null },
  { name: 'Treasure Maps', year: '1990', image: null as string | null },
  { name: 'Beer Bottle Caps', year: '1991', image: null as string | null },
  { name: 'Pogs', year: '1993', image: null as string | null },
  { name: 'Polly Pocket', year: '1993', image: null as string | null },
  { name: 'Care Bears (original)', year: '1994', image: null as string | null },
  { name: 'My Little Pony (original)', year: '1994', image: null as string | null },
  { name: "McDonald's Toys", year: '1995', image: null as string | null },
  { name: 'Lint from the dryer', year: '1996', image: null as string | null },
  { name: 'Crazy Bones', year: '1997', image: null as string | null },
  { name: 'Beanie Babies', year: '1997', image: null as string | null },
  { name: 'Pokémon Cards', year: '1999', image: null as string | null },
  { name: 'Analog Cameras', year: '2005', image: null as string | null },
  { name: 'Analog Journals', year: '2010', image: null as string | null },
  { name: 'NFTs', year: '2021', image: null as string | null },
  { name: 'Smart Doll', year: '2023', image: null as string | null },
  { name: 'Sweat Pants (COVID)', year: '2020', image: null as string | null },
  { name: 'VOX/STL/GLB files', year: '2022', image: null as string | null },
  { name: 'Plushie Dreadfuls', year: '2023', image: null as string | null },
];
*/

const SectionDivider = () => (
  <div className="flex items-center gap-3 my-16 md:my-20">
    <div className="flex-1 h-px bg-border" />
    <Star size={8} className="text-muted-foreground/30 fill-muted-foreground/30" />
    <Star size={12} className="text-muted-foreground/30 fill-muted-foreground/30" />
    <Star size={8} className="text-muted-foreground/30 fill-muted-foreground/30" />
    <div className="flex-1 h-px bg-border" />
  </div>
);

const ItemGrid = ({ items, onItemClick }: { items: { name: string; year: string; image: string | null; description?: string; objectPosition?: string }[]; onItemClick?: (item: any) => void }) => (
  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
    {items.map((item) => (
      <div
        key={item.name}
        className={`group ${item.description ? 'cursor-pointer' : ''}`}
        onClick={() => item.description && onItemClick?.(item)}
      >
        <div className="aspect-video overflow-hidden bg-muted/30 border border-border mb-2 flex items-center justify-center">
          {item.image ? (
            <img
              src={item.image}
              alt={item.name}
              loading="lazy"
              className="w-full h-full object-cover photo-grayscale"
              style={item.objectPosition ? { objectPosition: item.objectPosition } : undefined}
            />
          ) : (
            <span className="text-[10px] text-muted-foreground/50 text-center px-1 font-mono">{item.name}</span>
          )}
        </div>
        <p className="text-[10px] text-muted-foreground leading-tight">{item.name}</p>
        <p className="text-[9px] text-muted-foreground/50 font-mono">{item.year}</p>
      </div>
    ))}
  </div>
);

/* Metaverse worlds - commented out for now
const metaverseWorlds = [
  { name: 'Second Life', year: '2003', image: null },
  { name: 'Voxels (Cryptovoxels)', year: '2018', image: null },
  { name: 'Decentraland', year: '2020', image: null },
  { name: 'Substrata', year: '2021', image: null },
  { name: 'OnCyber', year: '2021', image: null },
  { name: 'Nifty Island', year: '2022', image: null },
  { name: 'Hyperfy', year: '2023', image: null },
  { name: 'The Man Who Sold The World', year: '2024', image: null },
];
*/

const Hobby = () => {
  const [selectedGame, setSelectedGame] = useState<typeof videoGames[0] | null>(null);

  return (
    <PageLayout>
      <span className="section-label block mb-4">Hobbies</span>
      <h1 className="headline-section mb-12">Side Projects</h1>

      {/* Brewing & Selling Tomorrow - top row */}
      <div className="grid md:grid-cols-2 gap-6 mb-8">
        {sideProjects.map((project) => {
          const card = (
            <>
              <div className="aspect-[16/9] bg-muted/30 border border-border mb-4 overflow-hidden group-hover:border-foreground transition-colors flex items-center justify-center">
                {project.title === "Phosphor's Gallery" ? (
                  <div className="w-full h-full grayscale group-hover:grayscale-0 transition-all duration-500">
                    <AgentGalleryThumbnail />
                  </div>
                ) : project.image ? (
                  <img
                    src={project.image as string}
                    alt={project.title}
                    loading="eager"
                    className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-500"
                    style={'objectPosition' in project && project.objectPosition ? { objectPosition: project.objectPosition as string } : undefined}
                  />
                ) : (
                  <span className="text-sm text-muted-foreground/40 font-mono">{project.title}</span>
                )}
              </div>
              <span className="mono-label block mb-1">{project.subtitle}</span>
              <h3 className="font-serif text-xl font-semibold text-foreground mb-1">{project.title}</h3>
              <p className="body-secondary text-sm">{project.tagline}</p>
            </>
          );

          if ('link' in project && project.link) {
            return (
              <a key={project.title} href={project.link} target="_blank" rel="noopener noreferrer" className="group block">
                {card}
              </a>
            );
          }
          return <div key={project.title} className="group">{card}</div>;
        })}
      </div>

      {/* Hobbies grid */}
      <div className="grid md:grid-cols-3 gap-6 mb-24">
        {hobbies.map((hobby) => {
          const content = (
            <>
              <div className={`aspect-[16/9] border border-border mb-4 overflow-hidden group-hover:border-foreground transition-colors flex items-center justify-center ${'objectFit' in hobby && hobby.objectFit === 'contain' ? 'bg-[#1a2420]' : 'bg-muted/30'}`}>
                {'video' in hobby && hobby.video ? (
                  <video
                    src={hobby.video as string}
                    muted
                    playsInline
                    preload="metadata"
                    className="w-full h-full object-cover grayscale"
                  />
                ) : hobby.image ? (
                  <img
                    src={hobby.image}
                    alt={hobby.title}
                    loading="lazy"
                    className={`w-full h-full ${'objectFit' in hobby && hobby.objectFit === 'contain' ? 'object-contain' : 'object-cover'} grayscale group-hover:grayscale-0 transition-all duration-500`}
                  />
                ) : (
                  <span className="mono-label text-muted-foreground group-hover:text-foreground transition-colors">{hobby.title} ↗</span>
                )}
              </div>
              <span className="mono-label block mb-1">{hobby.subtitle}</span>
              <h3 className="font-serif text-xl font-semibold text-foreground mb-1">{hobby.title}</h3>
              <p className="body-secondary text-sm">{hobby.tagline}</p>
            </>
          );

          if ('link' in hobby && hobby.link) {
            return (
              <a key={hobby.title} href={hobby.link} target="_blank" rel="noopener noreferrer" className="group block">
                {content}
              </a>
            );
          }
          return (
            <div key={hobby.title} className="group">
              {content}
            </div>
          );
        })}
      </div>

      <SectionDivider />

      {/* Favorite Games */}
      <div id="games">
        <h2 className="headline-section mb-10">Favorite Games</h2>
        
        <div className="mb-12 space-y-5 text-muted-foreground">
          <p className="text-lg leading-relaxed">
            I've studied games my entire life, not just as a player but as a designer reverse-engineering why they work. The best games nail what most software struggles with: <strong>teaching complex systems through play</strong>, <strong>rewarding mastery without punishing newcomers</strong>, and <strong>creating economies that self-balance</strong>. Many of my favorites are children's games, because if a five-year-old can figure it out without a tutorial, that's the bar your enterprise SaaS onboarding should be hitting. That lens informs every product decision I make for <em>usability</em>, <em>accessibility</em>, and <em>scalability</em>.
          </p>
        </div>

        <ItemGrid items={videoGames} onItemClick={(item) => setSelectedGame(item)} />

        <p className="text-lg leading-relaxed text-muted-foreground mt-16">
          The games and platforms that last are the ones where users build something the designers never anticipated.
        </p>
        <p className="text-lg leading-relaxed text-muted-foreground mt-2">
          That's the bar I aim for: <strong>simple entry, deep mastery, room for people to make it theirs</strong>.
        </p>
      </div>

      {/* Metaverse - commented out for now
      <SectionDivider />
      <div>
        <h2 className="headline-section mb-10">Metaverse (Virtual Worlds)</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {metaverseWorlds.map((item) => (
            <div key={item.name} className="group">
              <div className="aspect-video overflow-hidden bg-muted/30 border border-border mb-2 flex items-center justify-center">
                <span className="text-[10px] text-muted-foreground/50 text-center px-1 font-mono">{item.name}</span>
              </div>
              <p className="text-[10px] text-muted-foreground leading-tight">{item.name}</p>
              <p className="text-[9px] text-muted-foreground/50 font-mono">{item.year}</p>
            </div>
          ))}
        </div>
      </div>

      <SectionDivider />

      <div>
        <h2 className="headline-section mb-10">Collections</h2>
        <ItemGrid items={collections} />
      </div>
      */}

      <GameDetailModal game={selectedGame} onClose={() => setSelectedGame(null)} />
    </PageLayout>
  );
};

export default Hobby;
